spring:
  sql:
    init:
      mode: always
      encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true      # (2) SQL 쿼리 출력
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC